tasks:
  - init: |
      sudo apt-get update
      sudo apt-get install -y openjdk-21-jdk
      sudo ln -sf /usr/lib/jvm/java-21-openjdk-amd64/bin/java $(which java)
      echo 'export JAVA_HOME=/usr/lib/jvm/java-21-openjdk-amd64' >> ~/.bashrc
      source ~/.bashrc
      mvn install -P quick-build
    command: |
      curl https://gist.githubusercontent.com/timja/fe73f0a0f98afe4d9356e7ce6752d95b/raw/98ad71080e91ed75824ec410ff905419e3788065/init.sh | bash
      # without host being `0.0.0.0` redirects will go to localhost ignoring the forwarded values for some reason
      mvn hpi:run -Dhost=0.0.0.0
    name: Run
  - command: gp ports await 8080 && gp url 8080 && gp preview $(gp url 8080)/jenkins/
    name: Preview

github:
  prebuilds:
    pullRequestsFromForks: true
    addBadge: true

jetbrains:
  intellij:
    plugins:
      - Stapler plugin for IntelliJ IDEA
    prebuilds:
      version: stable
