tasks:
  - init: |
      echo "sdkman_auto_answer=true" > $HOME/.sdkman/etc/config
      sdk install java 21.0.4-tem
      sdk use java 21.0.4-tem
      mvn install -P quick-build
    command: |
      curl https://gist.githubusercontent.com/timja/fe73f0a0f98afe4d9356e7ce6752d95b/raw/98ad71080e91ed75824ec410ff905419e3788065/init.sh | bash
      # without host being `0.0.0.0` redirects will go to localhost ignoring the forwarded values for some reason
      mvn hpi:run -Dhost=0.0.0.0
    name: Run
  - command: gp ports await 8080 && gp url 8080 && gp preview $(gp url 8080)/jenkins/
    name: Preview

github:
  prebuilds:
    pullRequestsFromForks: true
    addBadge: true

jetbrains:
  intellij:
    plugins:
      - Stapler plugin for IntelliJ IDEA
    prebuilds:
      version: stable
