tasks:
  - init: mvn install -P quick-build
    command: |
      curl https://gist.githubusercontent.com/timja/fe73f0a0f98afe4d9356e7ce6752d95b/raw/a8d772267bed81fb0c11af2c69eaa71ebc7daec0/init.sh | bash
      # without host being `0.0.0.0` redirects will go to localhost ignoring the forwarded values for some reason
      mvn hpi:run -Dhost=0.0.0.0
    name: Run
  - command: gp await-port 63342 && gp await-port 8080 && gp url 8080 && gp preview $(gp url 8080)/jenkins/
    name: Preview

github:
  prebuilds:
    pullRequestsFromForks: true
    addBadge: true

jetbrains:
  intellij:
    plugins:
      - Stapler plugin for IntelliJ IDEA
