tasks:
  - init: mvn install -P quick-build
    command: mvn hpi:run
  - command: gp await-port 8080 && gp url 8080 && gp preview $(gp url 8080)/jenkins

github:
  prebuilds:
    pullRequestsFromForks: true
