files:
  - source: '/src/main/resources/io/jenkins/plugins/designlibrary/**/*.properties'
    ignore:
      - '/src/main/resources/io/jenkins/plugins/designlibrary/**/%file_name%_%two_letters_code%.properties'
    translation: '/src/main/resources/io/jenkins/plugins/designlibrary/**/%file_name%_%two_letters_code%.properties'
    escape_quotes: 1
    escape_special_characters: 0
  - source: '/src/main/resources/lib/samples/**/*.properties'
    ignore:
      - '/src/main/resources/lib/samples/**/%file_name%_%two_letters_code%.properties'
    translation: '/src/main/resources/lib/samples/**/%file_name%_%two_letters_code%.properties'
    escape_quotes: 1
    escape_special_characters: 0

project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN
